### ISSUE TITLE
configure incorrectly treats gio and glib as the same library

### ISSUE THREAD

**Issue by AlexanderKurtz** [envelope-project/laik#123]
The ```configure``` script currently contains this:

```python
# run pkg-config for glib-2 cflags
glib_inc = os.popen('pkg-config --cflags gio-2.0').read().strip()
if glib_inc:
    glib_libs = os.popen('pkg-config --libs gio-2.0').read().strip()
    print("TCP backend enabled (glib-2.0/gio-2.0 found).")
    defs += " -DUSE_TCP"
    miscvars += "USE_TCP=1\n"
    miscvars += "TCP_INC=" + glib_inc + "\n"
    miscvars += "TCP_LIBS=" + glib_libs + "\n"
    test_subdirs += " tcp"
else:
    print("TCP backend disabled: glib-2.0/gio-2.0 not found")
    print("  On Ubuntu, install 'libglib2.0-dev'")
```

This is incorrect, gio and glib are **not** the same library, their CFLAGS/LDFLAGS may be similar but they are not identical:

```
$ pkg-config --cflags gio-2.0
-pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
$ pkg-config --cflags glib-2.0
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
$ pkg-config --libs gio-2.0
-lgio-2.0 -lgobject-2.0 -lglib-2.0
$ pkg-config --libs glib-2.0
-lglib-2.0
$ 
```

**Comment by weidendo** [comment]
Of course this is easy to change.

But, and correct me if I am wrong: both the flags and libs for "gio-2.0" obviously are a superset of the ones of "glib-2.0". My natural assumption from that was that "gio-2.0" depends on "glib-2.0" (which makes sense).

My understanding is that the flags/libs provided by pkg-config for a library always include the flags/libs of libraries the given libary is dependend on - otherwise, compiling or linking most probably would fail.

So why include the flags/libs for "glib-2.0" twice?

**Comment by AlexanderKurtz** [comment]
Well, your logic assumes that gio does and will always depend on glib. If this is OK for you, this issue can of course be closed!

**Comment by weidendo** [comment]
As gio/glib are from the same project, and my understanding is that glib provides the base functionality, I do not think this ever will change.
