### ISSUE TITLE
TCP backend: remove bloat from old copy of the MPI backend (ie. just exec actions)

### ISSUE THREAD

**Issue by weidendo** [envelope-project/laik#163]
The TCP backend originally was able to use the MPI backend code (with slight mods), as it just reimplemented some MPI functions via TCP. But the current version has some additional API between the current tcp/backend.c and the "miniMPI" implementation for the sake of optimizations, e.g. using 2-step reductions. However, in the MPI backend this now is abstracted away as an backend-independent action sequence transformation (laik_aseq_splitReduce), which is just used.

The TCP backend really should use the "middle layer" code "backend_mpi.c" now, for the TCP backend to become driven by action sequences. This should be done soon, as the MPI backend will be used to implement new optimizations possible with MPI but not with miniMPI.

@AlexanderKurtz: is this still possible? I want to use IRecv in the MPI backend to trigger receives as early as possible. How tricky is it to do IRecv / wait in miniMPI?

**Comment by AlexanderKurtz** [comment]
This should still be possible, but the MiniMPI-Layer does not offer ISend/IRecv at the moment, but transparently converts the regular Send/Receive calls to work asynchronously (by copying the messages to/from input/output buffers up to a size limit).  Adding ISend/IRecv should be simple though, just make ISend/IRecv a wrapper around the regular Send/Receive functions and create NOOP Wait/Probe functions. However, this approach obviously does not guarantee that the message has actually been delivered when MPI_Wait() returns. But then again, regular MPI also does not guarantee this, the message may still well be in some OS or network buffer.

With that being said, I don't think having both backends share the same ```backend_mpi.c``` is a good idea. The TCP backend works differently than a regular MPI implementation (aggressive buffering, threads, etc.) and it only offers a **very small** subset of the MPI API. Most importantly, it doesn't allow anything except 1:1 communication, i.e. source/dest ranks < 0 will lead to errors (actually, the MiniMPI layer expects the rank argument to be a ```size_t``` instead of an ```int``` for precisely this reason).

**Comment by weidendo** [comment]
Any backend just should execute action seqences, and is allowed to do transformations on these actions before. There is no need for a backend to have to implement all possible actions, as the tranformations can be done such that only a few action types are left over.
In this sense, the current tcp/backend.c is "technical debt", as it does not follow this design. For me, it just seemed easiest to replace it with the current MPI backend code. Do you think another approach is better?

It really would be cool if the asynchronity available in the TCP backend can be used by LAIK.
Let's talk only about IRecv for now. What pair of actions would reflect the implemented
asynchronity in the TCP backend? I would expect that the first should set up message reception without blocking, and only the 2nd action would block if the message was not yet received.
Do this things relate to 2 different function calls within your implementation? If so, problem solved :-)

**Comment by weidendo** [comment]
Regarding ranks: negative ranks always are an error in MPI. But so are ranks higher than the number of processes. Just making the type unsigned also cannot enforce the latter. So I do not see the point of using "size_t".

**Comment by weidendo** [comment]
Commit 8cc994 updates the implementation of the backend API in the TCP backend with most of
what the MPI backend does (no async Send/Recv for now).

Closing.
